### ISSUE TITLE
Nothing works?

### ISSUE THREAD

**Issue by CazzoPMX** [Petrascyll/gui_collect#4]
Uhh.... I don't want to be rude.... but I can't do anything with this tool, nor does any of these buttons work
And when I try to reconfigure it to HSR via that config file, it just crashes with NullRef Errors.

And yes, I do have Python and all that stuff, I am Programming regularly.

**Comment by Petrascyll** [comment]
You probably missed filling in a required input field. The app will print errors in the console which is not very user friendly I know, but working on it... You must select the correct frame analysis folder, provide at least 1 valid IB hash, and enter an Extract Name.
 
> And when I try to reconfigure it to HSR via that config file, it just crashes with NullRef Errors.

Thats expected, the button is not there for a reason. Hsr and ZZZ are very similar to dump so you can get away with using the zzz button to dump Hsr objects though. Hsr dedicated button and some more features are still on dev branch for now.
