### ISSUE TITLE
Thank you for your software, but I encountered a problem while using it.

### ISSUE THREAD

**Issue by newandstar** [Petrascyll/gui_collect#6]
gui_collect-main\backend\analysis\FrameAnalysis.py", line 82
    f'collect_model_data = {component.options['collect_model_data']}, '
                                               ^^^^^^^^^^^^^^^^^^
SyntaxError: f-string: unmatched '[' 

"I modified line 82 of [FrameAnalysis.py](http://frameanalysis.py/) from f'collect_model_data = {component.options['collect_model_data']}, ' to f'collect_model_data = {component.options['collect_model_data']}, ' but it prompts an argument error when opened."

**Comment by newandstar** [comment]
Tk_ GetPixmap: Error from CreateDIBSection X

**Comment by Petrascyll** [comment]
Thanks for letting me know. Seems like I used syntax thats only supported in the latest version of python - v3.12. It should work again with py v3.9 - v3.11 with the commit I just pushed 39d3eba4ab4f9b4e184c594b76c472a45d0a2977

**Comment by newandstar** [comment]
I have successfully solved this problem; the solution was to reinstall the operating system. Thank you very much for your tool, and I hope it continues to improve in the future. Thank you.
